### ISSUE TITLE
[Translation][br] Brazilian Portuguese translation organization

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaDocs/Julia-Cheat-Sheet#49]
Organização de tradução

- Indique qual arquivo você irá traduzir **antes de começar** para que ninguém duplique o esforço.
- Abra um Pull Request com sua tradução, colocando `[br]` no cabeçalho.
- alguém deve verificar o que você fez, comentar possíveis mudanças, e aceitar seu PR.

Se você puder ser revisor, avise.

O que precisa ser feito:

- [ ] Revisar #48, porque foi aceito sem ler
- [ ] Portar #46 e #45
- [ ] _data/blocks.yml (add `br` entry separately)
- [x] Arrays.md (#48)
- [x] Basics.md (#48)
- [ ] Characters-and-strings.md (#61)
- [ ] Collection-functions.md
- [x] Control-flow-and-loops.md (#57)
- [ ] DataFrames.md (#52)
- [x] Dictionaries.md (#75)
- [ ] Exceptions.md (#68)
- [ ] Expressions.md (#66)
- [ ] Functions.md (#55)
- [ ] IDEs-Editors-and-Plugins.md
- [x] IO.md (#64)
- [ ] Introspection-and-reflection.md (#53)
- [ ] Linear-Algebra.md (#59)
- [x] Macros.md (#70)
- [ ] Missing-and-Nothing.md (#54)
- [x] Modules.md (#77)
- [ ] Naming-Conventions.md (#67)
- [ ] Noteworthy-packages-and-projects.md
- [x] Numbers.md (#58)
- [x] Operators.md (#56)
- [ ] Package-management.md
- [ ] Parallel-Computing.md
- [ ] Performance-tips.md
- [x] Random-Numbers.md (#65)
- [ ] Resources.md
- [ ] Sets.md (#51)
- [x] Standard-libraries.md (#60)
- [ ] The-shell-aka-REPL.md
- [x] Types.md (#76)
- [ ] Videos.md (#62)
- [ ] What-is.md

**Comment by HektorDannyel** [comment]
Irei traduzir Random-Numbers.md

**Comment by shbr** [comment]
Irei trabalhar em Sets.md

**Comment by pps18** [comment]
Vou traduzir sobre funções.

**Comment by gustavosarturi** [comment]
Irei traduzir "Linear Algebra" e "Expressions"

**Comment by jaquelineortiz** [comment]
Irei traduzir "Numbers"

**Comment by marianamds** [comment]
Irei traduzir o "Package management"

**Comment by leticiaoliv** [comment]
Characters-and-strings

**Comment by phls** [comment]
Irei traduzir Videos.md

**Comment by voceperdeuseutempolendoisso** [comment]
Missing and nothing

**Comment by d0uki** [comment]
Irei traduzir Control-flow-and-loops.md

**Comment by horstmannmat** [comment]
Eu  irei de I/O

**Comment by marianamds** [comment]
Irei traduzir "Introspection and reflection"

**Comment by Victor-Alflen** [comment]
Irei traduzir Standard-libraries.md

**Comment by DanteSP01** [comment]
vou nesse Random-Numbers.md

**Comment by chunggnuhc** [comment]
Vou traduzir Operators.md

**Comment by gustavosarturi** [comment]
Irei traduzir "Naming Conventions"

**Comment by gustavosarturi** [comment]
Irei traduzir "Exceptions"

**Comment by d0uki** [comment]
Traduzirei macros.md

**Comment by leticiaoliv** [comment]
Irei traduzir Noteworthy packages and projects

**Comment by waldyrious** [comment]
@abelsiqueira, quando esta ronda de traduções terminar, talvez seja uma boa ideia renomear a pasta `br` para `pt-br`, não achas? No contexto linguístico, `br` é o código para o [bretão](https://pt.wikipedia.org/wiki/L%C3%ADngua_bret%C3%A3), o que pode ser confuso.

**Comment by abelsiqueira** [comment]
Olá @waldyrious, obrigado pela dica, farei isso sim.

**Comment by mjr** [comment]
Irei traduzir "Dictionaries"

**Comment by guilhermebferreira** [comment]
irei traduzir Performance-tips.md

**Comment by guilhermebferreira** [comment]
irei traduzir What-is
